services:
  php:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    restart: unless-stopped
    environment:
      - APP_URL=${URL}
    volumes:
      - './database:/var/www/html/database/sqlite'
      - './logs:/var/www/html/storage/logs'
      - './private:/var/www/html/storage/app/private'
      - './typesense:/var/www/html/typesense'
    ports:
      - 8012:8080
    labels:
      - homepage.group=Tools
      - homepage.name=Notes
      - homepage.icon=nextcloud-notes
      - homepage.href=${URL}
