networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo/forgejo:16
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=${TZ}
    restart: unless-stopped
    labels:
      - homepage.group=Productivity
      - homepage.name=Forgejo
      - homepage.icon=forgejo
      - homepage.href=${URL}
    networks:
      - forgejo
    volumes:
      - './data:/data'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '${PORT:-3005}:3000'
      - '${SSH_PORT:-222}:22'
