services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - './config:/config'
      - '/etc/localtime:/etc/localtime:ro'
      - '/run/dbus:/run/dbus:ro'
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Home Assistant
      - homepage.icon=home-assistant
      - homepage.href=${URL}
      - homepage.widget.type=homeassistant
      - homepage.widget.url=${URL}
      - homepage.widget.key=${HOME_ASSISTANT_ACCESS_TOKEN}
