---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    uptime: true
    disk:
      - /
      - "{{HOMEPAGE_VAR_MEDIA_DISK_PATH}}"
    units: metric
    network: true

- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    locale: en-GB
    format:
      dateStyle: short
      timeStyle: short
      hourCycle: h23

- openmeteo:
    label: "{{HOMEPAGE_VAR_WEATHER_LABEL}}" # optional
    latitude: {{HOMEPAGE_VAR_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_LONGITUDE}}
    timezone: "{{HOMEPAGE_VAR_TZ}}" # optional
    units: metric # or imperial
    cache: 10 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
