services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - HARDCOVER_TOKEN=${HARDCOVER_API_KEY}
      - NETWORK_SHARE_MODE=false
      - CWA_PORT_OVERRIDE=8083
    volumes:
      - './calibre-web/config:/config'
      - '${INGEST_PATH}:/cwa-book-ingest'
      - '${CALIBRE_LIBRARY_PATH}:/calibre-library'
    ports:
      - '${CALIBRE_WEB_PORT:-8083}:8083'
    labels:
      - homepage.group=Books
      - homepage.name=Calibre Web Automated
      - homepage.icon=calibre-web
      - homepage.href=${CALIBRE_WEB_HOMEPAGE_URL}
    restart: unless-stopped
